name: blockpush_lowdim_seed_abs

obs_dim: 16
action_dim: 2
keypoint_dim: 2
obs_eef_target: True

env_runner:
  _target_: diffusion_policy.env_runner.blockpush_lowdim_runner.BlockPushLowdimRunner
  n_train: 6
  n_train_vis: 2
  train_start_seed: 0
  n_test: 50
  n_test_vis: 4
  test_start_seed: 100000
  max_steps: 350
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 5
  past_action: ${past_action_visible}
  abs_action: True
  obs_eef_target: ${task.obs_eef_target}
  n_envs: null

dataset:
  _target_: diffusion_policy.dataset.blockpush_lowdim_dataset.BlockPushLowdimDataset
  zarr_path: data/block_pushing/multimodal_push_seed_abs.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  obs_eef_target: ${task.obs_eef_target}
  use_manual_normalizer: False
  seed: 42
  val_ratio: 0.02
